### PR TITLE
Added option to generate Mi Bindkey with Password

### PR DESCRIPTION
**Pull request by JsBergbau**
Added option added to generate Mi Bindkey with Password as described here https://github.com/pvvx/ATC_MiThermometer/issues/94#issuecomment-847142307

### CODE REVIEW

**Comment by JsBergbau** [comment]
Hi @pvvx ,
what do you need or can I do that you can merge this pull request and thus integrate mi bindkey generation of password? This is just an addidional feature so bind key can also be set like before.

**Comment by pvvx** [comment]
Inappropriate license for argon2-bundled.min.js:
_"The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."_
There is no such part in my antics.
This is the bomb planted by Linus Torvalds, which created the conditions for the spread of open-source.

**Comment by JsBergbau** [comment]
This license text is included in argon2-bundled.min.js so I thought this is sufficient, because argon2-bundled.min.js is a software on its own....

**Comment by JsBergbau** [comment]
So it is ok how the license is included in the file itself?
Or would it help to fetch the file from somewhere else, like a CDN?

**Comment by JsBergbau** [comment]
@pvvx What can I do that it can be integrated to generate MiBindKey from password? How can I help you?

**Comment by JsBergbau** [comment]
@pvvx I'd really like to support the new encrypted format and generate the bindkey via a simple password. So it would be really great when this pull request can be integrated. So please just tell me what can I do, that you can integrate it. Thank you very much in advance.

**Comment by h1618** [comment]
> Inappropriate license for argon2-bundled.min.js:
> _"The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."_
> There is no such part in my antics.
> This is a bomb planted by open source traitor Linus Torvalds, who created conditions for the dissemination of information.
> You must include all your teachers and parents. Otherwise, this license is invalid.

Excuse me, but this is bullshit. This wording is verbatim from the MIT License. You may not like it, but it is far more liberal than the GPL - and it has nothing to do with Linus Torvalds.

**Comment by JsBergbau** [comment]
@pvvx Hi Victor,
can you have a look again at this pull request? What do you need / can I do to get this integrated? There's the request to support encrypted ATC format https://github.com/JsBergbau/MiTemperature2/issues/93 and I'd like to add support for encrypted ATC format with bindkey direct and bindkey derived of password.

**Comment by rocket59** [comment]
Hi @pvvx first off many thanks for your work in improving on ATC'S firmware! A cool and cheap thermometer now made much better!

As I raised the issue of using encrypted advertisements on @JsBergbau's git page, I would like to add my support to adding password bindkey generation to the flasher to make it easier to make the transmissions more secure. Thanks for considering!

**Pull request closed without merging**
